name: Build and Deploy to Github Pages

on: push
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4


      # Use GitHub Deploy Action to build and deploy to Github
      - uses: jeffreytse/jekyll-deploy-action@v0.6.0
        with:
          provider: 'github'
          branch: "github-pages"
          token: ${{ secrets.GITHUB_TOKEN }} # It's your Personal Access Token(PAT)
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          cname: 'approvaltests.com'    
          
